(function(g){var window=this;var sEa=function(a,b){return g.Xb(a,b)},c6=function(a){g.Rn(a,"zx",g.xc());
return a},d6=function(a,b,c){g.Ga(c)||(c=[String(c)]);
g.Un(a.o,b,c)},tEa=function(a,b){var c=[];
g.El(b,function(a){try{var b=g.sE.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Aa(b)?g.rE(b)&&c.push(a):c.push(a)},a);
return c},uEa=function(a,b){var c=tEa(a,b);
(0,g.C)(c,function(a){g.sE.prototype.remove.call(this,a)},a)},vEa=function(a){if(a.Nd){if(a.Nd.locationOverrideToken)return{locationOverrideToken:a.Nd.locationOverrideToken};
if(null!=a.Nd.latitudeE7&&null!=a.Nd.longitudeE7)return{latitudeE7:a.Nd.latitudeE7,longitudeE7:a.Nd.longitudeE7}}return null},wEa=function(a,b,c,d){var e=new g.In(null,void 0);
a&&g.Jn(e,a);b&&g.Kn(e,b);c&&g.Ln(e,c);d&&g.Mn(e,d);return e},e6=function(a,b){g.kF[a]=!0;
var c=g.iF();c&&c.publish.apply(c,arguments);g.kF[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.C=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Cn;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",xEa(this,a.capabilities||""),yEa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},xEa=function(a,b){a.capabilities.clear();
(0,g.qe)(b.split(","),g.Ma(sEa,zEa)).forEach(function(b){a.capabilities.add(b)})},yEa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},AEa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},BEa=function(a){return new g6(a)},CEa=function(a){return g.Ga(a)?(0,g.I)(a,BEa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return g.Ga(a)?"["+(0,g.I)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},DEa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},l6=function(a,b){return g.Sa(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},m6=function(a,b){return g.Sa(a,function(a){return h6(a,b)})},EEa=function(){var a=(0,g.vI)();
a&&uEa(a,a.o.de(!0))},n6=function(){var a=g.yI("yt-remote-connected-devices")||[];
g.rb(a);return a},FEa=function(a){if(g.Xa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},GEa=function(a){g.xI("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.yI("yt-remote-device-id");a||(a=k6(),g.xI("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.Wa(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.Wa(a,b);g.AI()&&g.tb(a,b);a=FEa(a);if(g.Xa(a))try{g.VH("remote_sid")}catch(c){}else try{g.UH("remote_sid",a.join(","),-1)}catch(c){}},HEa=function(){return g.yI("yt-remote-session-browser-channel")},IEa=function(){return g.yI("yt-remote-local-screens")||[]},JEa=function(){g.xI("yt-remote-lounge-token-expiration",!0,86400)},KEa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(IEa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.Lj)(c,function(a){return!g.Wa(b,a)})&&JEa();
g.xI("yt-remote-local-screens",a,31536E3)},LEa=function(a,b){g.xI("yt-remote-session-browser-channel",a);
g.xI("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.Wa(c,d)||c.push(d);GEa(c);q6()},r6=function(a){a||(g.zI("yt-remote-session-screen-id"),g.zI("yt-remote-session-video-id"));
q6();a=n6();g.ab(a,p6());GEa(a)},MEa=function(){if(!s6){var a=g.DE();
a&&(s6=new g.mE(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},t6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},NEa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},u6=function(a){a.length?OEa(a.shift(),function(){u6(a)}):v6()},PEa=function(a){return"chrome-extension://"+a+w6},OEa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},v6=function(){var a=NEa();
a&&a(!1,"No cast extension found")},REa=function(){if(QEa){var a=2,b=NEa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;OEa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",v6,c)}},SEa=function(){REa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);u6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+w6,"//www.gstatic.com/eureka/clank"+w6])},x6=function(a,b,c){g.J.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.Gd=b;this.D=(0,g.A)(this.hL,this);this.o=!1;this.A=0;this.C=this.Fa=null;this.B=[]},y6=function(){},z6=function(a,b,c,d){this.o=a;
this.C=b;this.G=c;this.F=d||1;this.B=45E3;this.Z=new g.Yn(this);this.A=new g.Tg;this.A.setInterval(250)},UEa=function(a,b,c){a.ak=1;
a.Ah=c6(b.clone());a.ij=c;a.D=!0;TEa(a,null)},A6=function(a,b,c,d,e){a.ak=1;
a.Ah=c6(b.clone());a.ij=null;a.D=c;e&&(a.XF=!1);TEa(a,d)},TEa=function(a,b){a.Vk=(0,g.H)();
B6(a);a.Zh=a.Ah.clone();d6(a.Zh,"t",a.F);a.co=0;a.Uc=a.o.fu(a.o.Un()?b:null);0<a.Nu&&(a.jr=new g.lm((0,g.A)(a.iH,a,a.Uc),a.Nu));a.Z.X(a.Uc,"readystatechange",a.jV);var c=a.Gi?g.hc(a.Gi):{};a.ij?(a.ks="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Uc.send(a.Zh,a.ks,a.ij,c)):(a.ks="GET",a.XF&&!g.ee&&(c.Connection="close"),a.Uc.send(a.Zh,a.ks,null,c));a.o.Bf(1)},XEa=function(a,b,c){for(var d=!0;!a.ni&&a.co<c.length;){var e=VEa(a,c);
if(e==C6){4==b&&(a.Bh=4,D6(15),d=!1);break}else if(e==WEa){a.Bh=4;D6(16);d=!1;break}else E6(a,e)}4==b&&0==c.length&&(a.Bh=1,D6(17),d=!1);a.Hf=a.Hf&&d;d||(F6(a),G6(a))},VEa=function(a,b){var c=a.co,d=b.indexOf("\n",c);
if(-1==d)return C6;c=Number(b.substring(c,d));if(isNaN(c))return WEa;d+=1;if(d+c>b.length)return C6;var e=b.substr(d,c);a.co=d+c;return e},ZEa=function(a,b){a.Vk=(0,g.H)();
B6(a);var c=b?window.location.hostname:"";a.Zh=a.Ah.clone();g.Rn(a.Zh,"DOMAIN",c);g.Rn(a.Zh,"t",a.F);try{a.Jf=new ActiveXObject("htmlfile")}catch(n){F6(a);a.Bh=7;D6(22);G6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in H6)k=H6[l];else if(l in YEa)k=H6[l]=YEa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
H6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Gd(g.Uc("b/12014412"),d+"</body></html>");a.Jf.open();a.Jf.write(g.ud(c));a.Jf.close();a.Jf.parentWindow.m=(0,g.A)(a.qU,a);a.Jf.parentWindow.d=(0,g.A)(a.jF,a,!0);a.Jf.parentWindow.rpcClose=(0,g.A)(a.jF,a,!1);c=a.Jf.createElement("DIV");a.Jf.parentWindow.document.body.appendChild(c);d=g.hd(a.Zh.toString());d=g.sc(g.ed(d));d=g.Gd(g.Uc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Cd(c,g.ud(d));a.o.Bf(1)},B6=function(a){a.Gy=(0,g.H)()+
a.B;
$Ea(a,a.B)},$Ea=function(a,b){if(null!=a.zl)throw Error("WatchDog timer not null");
a.zl=I6((0,g.A)(a.FU,a),b)},J6=function(a){a.zl&&(g.v.clearTimeout(a.zl),a.zl=null)},G6=function(a){a.o.TB()||a.ni||a.o.Nq(a)},F6=function(a){J6(a);
g.Ff(a.jr);a.jr=null;a.A.stop();g.eo(a.Z);if(a.Uc){var b=a.Uc;a.Uc=null;b.abort();b.dispose()}a.Jf&&(a.Jf=null)},E6=function(a,b){try{a.o.cF(a,b),a.o.Bf(4)}catch(c){}},bFa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;aFa(a,b,function(e){e?c(!0):g.v.setTimeout(function(){bFa(a,b,c,d,f)},f)})}},aFa=function(a,b,c){var d=new Image;
d.onload=function(){try{K6(d),c(!0)}catch(e){}};
d.onerror=function(){try{K6(d),c(!1)}catch(e){}};
d.onabort=function(){try{K6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},K6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},cFa=function(a){this.o=a;
this.A=new y6},dFa=function(a){var b=L6(a.o,a.Rl,"/mail/images/cleardot.gif");
c6(b);bFa(b.toString(),5E3,(0,g.A)(a.iK,a),3,2E3);a.Bf(1)},N6=function(a){var b=a.o.I;
if(null!=b)D6(5),b?(D6(11),M6(a.o,a,!1)):(D6(12),M6(a.o,a,!0));else if(a.pe=new z6(a,void 0,void 0,void 0),a.pe.Gi=a.Lu,b=a.o,b=L6(b,b.Un()?a.Jm:null,a.Mu),D6(5),!g.ce||g.Mc(10))d6(b,"TYPE","xmlhttp"),A6(a.pe,b,!1,a.Jm,!1);else{d6(b,"TYPE","html");var c=a.pe;a=!!a.Jm;c.ak=3;c.Ah=c6(b.clone());ZEa(c,a)}},O6=function(a,b,c){this.o=1;
this.A=[];this.B=[];this.D=new y6;this.H=a||null;this.I=null!=b?b:null;this.F=c||!1},eFa=function(a,b){this.o=a;
this.map=b;this.context=null},fFa=function(a){g.Hf.call(this,"statevent",a)},gFa=function(a,b){g.Hf.call(this,"timingevent",a);
this.size=b},hFa=function(a){g.Hf.call(this,"serverreachability",a)},kFa=function(a){iFa(a);
if(3==a.o){var b=a.Bn++,c=a.qp.clone();g.Rn(c,"SID",a.C);g.Rn(c,"RID",b);g.Rn(c,"TYPE","terminate");P6(a,c);b=new z6(a,a.C,b,void 0);b.ak=2;b.Ah=c6(c.clone());(new Image).src=b.Ah;b.Vk=(0,g.H)();B6(b)}jFa(a)},lFa=function(a){a.FK(1,0);
a.qp=L6(a,null,a.Ku);Q6(a)},iFa=function(a){a.ph&&(a.ph.abort(),a.ph=null);
a.zc&&(a.zc.cancel(),a.zc=null);a.Eg&&(g.v.clearTimeout(a.Eg),a.Eg=null);R6(a);a.je&&(a.je.cancel(),a.je=null);a.uh&&(g.v.clearTimeout(a.uh),a.uh=null)},mFa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new eFa(a.cQ++,b));2!=a.o&&3!=a.o||Q6(a)},Q6=function(a){a.je||a.uh||(a.uh=I6((0,g.A)(a.iF,a),0),a.Rj=0)},oFa=function(a,b){if(1==a.o){if(!b){a.Bn=Math.floor(1E5*Math.random());
var c=a.Bn++,d=new z6(a,"",c,void 0);d.Gi=null;var e=S6(a),f=a.qp.clone();g.Rn(f,"RID",c);g.Rn(f,"CVER","1");P6(a,f);UEa(d,f,e);a.je=d;a.o=2}}else 3==a.o&&(b?nFa(a,b):0==a.A.length||a.je||nFa(a))},nFa=function(a,b){if(b)if(6<a.ri){a.A=a.B.concat(a.A);
a.B.length=0;var c=a.Bn-1;var d=S6(a)}else c=b.G,d=b.ij;else c=a.Bn++,d=S6(a);var e=a.qp.clone();g.Rn(e,"SID",a.C);g.Rn(e,"RID",c);g.Rn(e,"AID",a.vk);P6(a,e);c=new z6(a,a.C,c,a.Rj+1);c.Gi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.je=c;UEa(c,e,d)},P6=function(a,b){if(a.Fd){var c=a.Fd.yB();
c&&g.Lb(c,function(a,c){g.Rn(b,c,a)})}},S6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.ri&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.ri?e:f-d;try{g.Lb(k,function(a,b){c.push("req"+f+"_"+b+"="+encodeURIComponent(a))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.A.splice(0,b));
return c.join("&")},pFa=function(a){a.zc||a.Eg||(a.G=1,a.Eg=I6((0,g.A)(a.hF,a),0),a.Hj=0)},T6=function(a){if(a.zc||a.Eg||3<=a.Hj)return!1;
a.G++;a.Eg=I6((0,g.A)(a.hF,a),qFa(a,a.Hj));a.Hj++;return!0},M6=function(a,b,c){a.es=c;
a.Vf=b.Rg;a.F||lFa(a)},R6=function(a){null!=a.ti&&(g.v.clearTimeout(a.ti),a.ti=null)},qFa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U6=function(a,b){if(2==b||9==b){var c=null;
a.Fd&&(c=null);var d=(0,g.A)(a.cW,a);c||(c=new g.In("//www.google.com/images/cleardot.gif"),c6(c));aFa(c.toString(),1E4,d)}else D6(2);rFa(a,b)},rFa=function(a,b){a.o=0;
a.Fd&&a.Fd.vA(b);jFa(a);iFa(a)},jFa=function(a){a.o=0;
a.Vf=-1;if(a.Fd)if(0==a.B.length&&0==a.A.length)a.Fd.Qt();else{g.fb(a.B);var b=g.fb(a.A);a.B.length=0;a.A.length=0;a.Fd.Qt(b)}},L6=function(a,b,c){var d=g.Sn(c);
if(""!=d.A)b&&g.Kn(d,b+"."+d.A),g.Ln(d,d.D);else{var e=window.location;d=wEa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.km&&g.Lb(a.km,function(a,b){g.Rn(d,b,a)});
g.Rn(d,"VER",a.ri);P6(a,d);return d},I6=function(a,b){if(!g.Ia(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},D6=function(a){V6.dispatchEvent(new fFa(V6,a))},sFa=function(){},tFa=function(a,b){this.action=a;
this.params=b||{}},W6=function(a,b){g.J.call(this);
this.o=new g.U(this.gU,0,this);g.K(this,this.o);this.Gd=5E3;this.A=0;if(g.Ia(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ia(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.C=a},X6=function(a,b,c){this.K=a;
this.F=b;this.C=new g.lE;this.A=new W6(this.FW,this);this.o=this.kb=null;this.Bb=!1;this.D=null;this.I="";this.H=this.B=0;this.G=[];this.L=c||!1},uFa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.es,sessionId:a.o.C,arrayId:a.o.vk}},vFa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&oFa(a.o),kFa(a.o));a.H=0},Y6=function(a){return!!a.o&&3==a.o.o},wFa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},Z6=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||document.location.href;var b=g.hh(a)||"";b&&(this.port=":"+b);this.domain=g.gh(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.A=!1))},$6=function(a,b){var c=a.o;
if(g.Aa(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.qh(c+b,{})},a7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ma(a.B,d,!0),onError:g.Ma(a.C,e),Kd:g.Ma(a.D,e)};c&&(a.Rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.TF(b,a)},AFa=function(){var a=xFa;
yFa();b7.push(a);zFa(b7)},c7=function(a,b){yFa();
var c=b7,d=BFa(a,String(b));g.Xa(c)?CFa(d):(zFa(c),(0,g.C)(c,function(a){a(d)}))},yFa=function(){b7||(b7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Da("yt.mdx.remote.debug.handlers_",b7,void 0))},CFa=function(a){var b=(d7+1)%50;
d7=b;e7[b]=a;f7||(f7=49==b)},zFa=function(a){var b=e7;
if(b[0]){var c=d7,d=f7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
e7=Array(50);d7=-1;f7=!1}},BFa=function(a,b){var c=((0,g.H)()-DFa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g7=function(a){g.V.call(this);
this.G=a;this.o=[]},EFa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},FFa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.qe)(a.o,function(a){return!!l6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=EFa(a,b[d])||c;return c},GFa=function(a,b){var c=a.o.length;
a.o=(0,g.qe)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},h7=function(a,b,c,d){g.V.call(this);
this.F=a;this.D=b;this.C=c;this.B=d;this.A=0;this.o=null;this.Fa=NaN},j7=function(a){g7.call(this,"LocalScreenService");
this.C=a;this.A=NaN;i7(this);this.info("Initializing with "+j6(this.o))},HFa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=$6(a.C,"/pairing/get_lounge_token_batch");
a7(a.C,c,{screen_ids:b.join(",")},(0,g.A)(a.vL,a),(0,g.A)(a.uL,a))}},i7=function(a){var b=CEa(IEa());
b=(0,g.qe)(b,function(a){return!a.uuid});
return FFa(a,b)},k7=function(a,b){KEa((0,g.I)(a.o,AEa));
b&&JEa()},m7=function(a,b){g.V.call(this);
this.F=b;var c=g.yI("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Wa(c,l)}this.o=d;this.D=a;this.C=this.B=NaN;this.A=null;l7("Initialized with "+g.Zg(this.o))},IFa=function(a,b,c){var d=$6(a.D,"/pairing/get_screen_availability");
a7(a.D,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},n7=function(a,b){a:if(g.Rb(b)!=g.Rb(a.o))var c=!1;
else{c=g.Ub(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(l7("Updated online screens: "+g.Zg(a.o)),a.o=b,a.U("screenChange"));JFa(a)},o7=function(a){isNaN(a.C)||g.hF(a.C);
a.C=g.fF((0,g.A)(a.zx,a),0<a.B&&a.B<(0,g.H)()?2E4:1E4)},l7=function(a){c7("OnlineScreenService",a)},KFa=function(a){var b={};
(0,g.C)(a.F(),function(a){a.token?b[a.token]=a.id:this.qc("Requesting availability of screen w/o lounge token.")});
return b},JFa=function(a){a=g.Ub(g.Nb(a.o,function(a){return a}));
g.rb(a);a.length?g.xI("yt-remote-online-screen-ids",a.join(","),60):g.zI("yt-remote-online-screen-ids")},p7=function(a){g7.call(this,"ScreenService");
this.F=a;this.A=this.C=null;this.B=[];this.D={};LFa(this)},NFa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.Ae();if(k=(c?m6(k,c):null)||m6(k,b)){k.uuid=b;var l=q7(a,k);IFa(a.A,l,function(a){e(a?l:null)})}else c?MFa(a,c,(0,g.A)(function(a){var f=q7(this,new g6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));IFa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},OFa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},MFa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.TF($6(a.F,"/pairing/get_lounge_token_batch"),e)},PFa=function(a){a.o=a.C.Ae();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.o))},LFa=function(a){r7(a);
a.C=new j7(a.F);a.C.subscribe("screenChange",(0,g.A)(a.JL,a));PFa(a);a.B=CEa(g.yI("yt-remote-automatic-screen-cache")||[]);r7(a);a.info("Initializing automatic screens: "+j6(a.B));a.A=new m7(a.F,(0,g.A)(a.Ae,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.U("onlineScreenChange")},a))},q7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),g.xI("yt-remote-automatic-screen-cache",(0,g.I)(a.B,AEa)));r7(a);a.D[b.uuid]=b.id;g.xI("yt-remote-device-id-map",a.D,31536E3);return b},r7=function(a){a.D=g.yI("yt-remote-device-id-map")||{}},s7=function(a,b,c){g.V.call(this);
this.M=c;this.I=a;this.A=b;this.C=null},t7=function(a,b){c7(a.M,b)},u7=function(a,b){s7.call(this,a,b,"CastSession");
this.o=null;this.B=0;this.F=(0,g.A)(this.LW,this);this.D=(0,g.A)(this.RU,this);this.B=g.fF((0,g.A)(function(){QFa(this,null)},this),12E4)},RFa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Zg(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.A)(function(){t7(this,"Failed to send message: getMdxSessionStatus.")},a)):t7(a,"Sending yt message without session: "+g.Zg(b))},QFa=function(a,b){g.hF(a.B);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.C||a.C.id!=b){var c=(0,g.A)(a.Oq,a),d=(0,g.A)(a.Fe,a);a.JB(b,c,d,5)}}else a.Fe(Error("Waiting for session status timed out."))},v7=function(a,b,c){s7.call(this,a,b,"DialSession");
this.B=this.H=null;this.K="";this.V=c;this.D=null;this.G=g.y;this.F=NaN;this.L=(0,g.A)(this.OW,this);this.o=g.y},SFa=function(a){a.o=a.I.mH(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(a){this.o=g.y;
this.Oq(a)},a),(0,g.A)(function(a){this.o=g.y;
this.Fe(a)},a))},TFa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.V;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}MEa()&&(b.env_useStageMdx=1);return g.oh(b)},w7=function(a,b){s7.call(this,a,b,"ManualSession");
this.o=g.fF((0,g.A)(this.xk,this,null),150)},x7=function(a,b,c,d){g.V.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.C=[];this.B=(0,g.A)(this.mT,this)},UFa=function(a,b){return b?g.Sa(a.C,function(a){return h6(b,a.label)},a):null},y7=function(a){c7("Controller",a)},xFa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},z7=function(a){return a.D||!!a.C.length||!!a.o},A7=function(a,b,c){b!=a.o&&(g.Ff(a.o),(a.o=b)?(c?a.U("yt-remote-cast2-receiver-resumed",b.A):a.U("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.fF,a,b)),b.C?a.U("yt-remote-cast2-session-change",b.C):c&&a.o.xk(null)):a.U("yt-remote-cast2-session-change",null))},VFa=function(a){var b=a.A.lH(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&h6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=UFa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new chrome.cast.Receiver(b,a.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},aGa=function(a,b,c,d,e,f,k){WFa()?XFa(b,e,f,k)&&(C7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?YFa(a,c):(window.__onGCastApiAvailable=function(b,d){b?YFa(a,c):(D7("Failed to load cast API: "+d),E7(!1),C7(!1),g.zI("yt-remote-cast-available"),g.zI("yt-remote-cast-receiver"),ZFa(),c(!1))},d?g.sF("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?SEa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?v6():(REa(),u6($Fa.map(PEa))))):B7("Cannot initialize because not running Chrome")},ZFa=function(){B7("dispose");
var a=F7();a&&a.dispose();g.Da("yt.mdx.remote.cloudview.instance_",null,void 0);bGa(!1);g.nF(G7);G7.length=0},H7=function(){return!!g.yI("yt-remote-cast-installed")},cGa=function(){var a=g.yI("yt-remote-cast-receiver");
return a?a.friendlyName:null},dGa=function(){B7("clearCurrentReceiver");
g.zI("yt-remote-cast-receiver")},eGa=function(){return H7()?F7()?F7().getCastSession():(D7("getCastSelector: Cast is not initialized."),null):(D7("getCastSelector: Cast API is not installed!"),null)},J7=function(){H7()?F7()?I7()?(B7("Requesting cast selector."),F7().requestSession()):(B7("Wait for cast API to be ready to request the session."),G7.push(g.mF("yt-remote-cast2-api-ready",J7))):D7("requestCastSelector: Cast is not initialized."):D7("requestCastSelector: Cast API is not installed!")},K7=
function(a,b){I7()?F7().setConnectedScreenStatus(a,b):D7("setConnectedScreenStatus called before ready.")},WFa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.WL||a},fGa=function(a,b){F7().init(a,b)},XFa=function(a,b,c,d){var e=!1;
F7()||(a=new x7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.xI("yt-remote-cast-available",a);e6("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){B7("onReceiverSelected: "+a.friendlyName);
g.xI("yt-remote-cast-receiver",a);e6("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){B7("onReceiverResumed: "+a.friendlyName);
g.xI("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){B7("onSessionChange: "+i6(a));
a||g.zI("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",a)}),g.Da("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
B7("cloudview.createSingleton_: "+e);return e},F7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},YFa=function(a,b){E7(!0);
C7(!1);fGa(a,function(a){a?(bGa(!0),g.pF("yt-remote-cast2-api-ready")):(D7("Failed to initialize cast API."),E7(!1),g.zI("yt-remote-cast-available"),g.zI("yt-remote-cast-receiver"),ZFa());b(a)})},B7=function(a){c7("cloudview",a)},D7=function(a){c7("cloudview",a)},E7=function(a){B7("setCastInstalled_ "+a);
g.xI("yt-remote-cast-installed",a)},I7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},bGa=function(a){B7("setApiReady_ "+a);
g.Da("yt.mdx.remote.cloudview.apiReady_",a,void 0)},C7=function(a){g.Da("yt.mdx.remote.cloudview.initializing_",a,void 0)},L7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.Zf=!1;this.I=this.H=this.A=this.B=0;this.C=NaN;this.D=!1;this.reset(a)},M7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Zf=!1;a.hasNext=!1;a.G=0;a.F=(0,g.H)();a.B=0;a.A=0;a.H=0;a.I=0;a.C=NaN;a.D=!1},N7=function(a){return a.sb()?((0,g.H)()-a.F)/1E3:0},O7=function(a,b){a.G=b;
a.F=(0,g.H)()},P7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Q7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&M7(a)},R7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ic(a.o);b.hasPrevious=a.Zf;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.B;b.seekableEnd=a.A;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.C;return b},T7=function(a,b){g.V.call(this);
this.o=0;this.B=a;this.F=[];this.D=new g.CD;this.C=this.A=null;this.I=(0,g.A)(this.MQ,this);this.G=(0,g.A)(this.En,this);this.H=(0,g.A)(this.LQ,this);this.K=(0,g.A)(this.YQ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Oy,this),gGa(this))):c=3;0!=c&&(b?this.Oy(c):g.fF((0,g.A)(function(){this.Oy(c)},this),0));
var d=eGa();d&&S7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},U7=function(a){return new L7(a.B.getPlayerContextData())},gGa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.B.subscribe(a,g.Ma(this.iT,a),this))},a)},hGa=function(a){(0,g.C)(a.F,function(a){this.B.unsubscribeByKey(a)},a);
a.F.length=0},V7=function(a,b){50>a.D.Hc()&&g.ED(a.D,b)},X7=function(a,b,c){var d=U7(a);
O7(d,c);-1E3!=d.playerState&&(d.playerState=b);W7(a,d)},Y7=function(a,b,c){a.B.sendMessage(b,c)},W7=function(a,b){hGa(a);
a.B.setPlayerContextData(R7(b));gGa(a)},S7=function(a,b){a.C&&(a.C.removeUpdateListener(a.I),a.C.removeMediaListener(a.G),a.En(null));
a.C=b;a.C&&(c7("CP","Setting cast session: "+a.C.sessionId),a.C.addUpdateListener(a.I),a.C.addMediaListener(a.G),a.C.media.length&&a.En(a.C.media[0]))},iGa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=U7(a);b.contentId!=d.videoId&&c7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;O7(d,a.A.getEstimatedTime());W7(a,d)}else c7("CP","No cast media video. Ignoring state update.")},Z7=function(a,b,c){return(0,g.A)(function(a){this.qc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.qc("Retrying "+b+" using MDx browser channel."),Y7(this,b,c))},a)},$7=function(a,b,c){g.V.call(this);
this.D=NaN;this.V=!1;this.K=this.I=this.L=this.M=NaN;this.O=[];this.B=this.G=this.C=this.ob=this.o=null;this.sa=a;this.O.push(g.VG(window,"beforeunload",(0,g.A)(this.lL,this)));this.A=[];this.ob=new L7;this.aa=b.id;this.o=jGa(this,c);this.o.subscribe("handlerOpened",this.QQ,this);this.o.subscribe("handlerClosed",this.NQ,this);this.o.subscribe("handlerError",this.OQ,this);this.o.subscribe("handlerMessage",this.PQ,this);wFa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=this.ob.videoId;
g.AI()&&g.xI("yt-remote-session-video-id",a)},this)},a8=function(a){c7("conn",a)},jGa=function(a,b){return new X6($6(a.sa,"/bc"),b)},b8=function(a,b){a.U("proxyStateChange",b)},kGa=function(a){a.D=g.fF((0,g.A)(function(){a8("Connecting timeout");
this.F(1)},a),2E4)},c8=function(a){g.hF(a.D);
a.D=NaN},d8=function(a){g.hF(a.M);
a.M=NaN},lGa=function(a){e8(a);
a.L=g.fF((0,g.A)(function(){f8(this,"getNowPlaying")},a),2E4)},e8=function(a){g.hF(a.L);
a.L=NaN},nGa=function(a,b){b&&(c8(a),d8(a));
b==(Y6(a.o)&&isNaN(a.D))?b&&(b8(a,1),f8(a,"getSubtitlesTrack")):b?(a.Y()&&a.ob.reset(),b8(a,1),f8(a,"getNowPlaying"),mGa(a)):a.F(1)},oGa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ob.videoId&&(g.cc(b.params)?a.ob.o=null:a.ob.o=b.params,a.U("remotePlayerChange"))},pGa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.ob.listId=b.params.listId||a.ob.listId;Q7(a.ob,c,d);a.U("remoteQueueChange")},rGa=function(a,b){b.params=b.params||{};
pGa(a,b);qGa(a,b);a.U("autoplayDismissed")},qGa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
O7(a.ob,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.ob.playerState&&(c=-1E3);a.ob.playerState=c;c=Number(b.params.loadedTime);a.ob.I=isNaN(c)?0:c;c=Number(b.params.duration);a.ob.H=isNaN(c)?0:c;c=a.ob;var d=Number(b.params.liveIngestionTime);c.C=d;c.D=isNaN(d)?!1:!0;c=a.ob;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.A=isNaN(e)?0:e;1==a.ob.playerState?lGa(a):e8(a);a.U("remotePlayerChange")},sGa=function(a,b){if(-1E3!=
a.ob.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ob.playerState=c;c=parseInt(b.params.currentTime,10);O7(a.ob,isNaN(c)?0:c);a.U("remotePlayerChange")}},tGa=function(a,b){var c="true"==b.params.muted;
a.ob.volume=parseInt(b.params.volume,10);a.ob.muted=c;a.U("remotePlayerChange")},uGa=function(a,b){a.G=b.params.videoId;
a.U("nowAutoplaying",parseInt(b.params.timeout,10))},vGa=function(a,b){var c="true"==b.params.hasNext;
a.ob.Zf="true"==b.params.hasPrevious;a.ob.hasNext=c;a.U("previousNextChange")},mGa=function(a){g.hF(a.K);
a.K=g.fF((0,g.A)(a.F,a,1),864E5)},f8=function(a,b,c){c?a8("Sending: action="+b+", params="+g.Zg(c)):a8("Sending: action="+b);
a.o.sendMessage(b,c)},g8=function(a){g7.call(this,"ScreenServiceProxy");
this.kd=a;this.A=[];this.A.push(this.kd.$_s("screenChange",(0,g.A)(this.JW,this)));this.A.push(this.kd.$_s("onlineScreenChange",(0,g.A)(this.HS,this)))},AGa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.YE("MDX_CONFIG")||b;EEa();q6();h8||(h8=new Z6(b?b.loungeApiHost:void 0),MEa()&&(h8.o="/api/loungedev"));i8||(i8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Da("yt.mdx.remote.deferredProxies_",i8,void 0));wGa();var c=j8();if(!c){var d=new p7(h8);g.Da("yt.mdx.remote.screenService_",d,void 0);c=j8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);aGa(a,d,function(a){a?k8()&&K7(k8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Da("yt.mdx.remote.initialized_",!0,void 0),l8("Initializing: "+g.Zg(b)),m8.push(g.mF("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),m8.push(g.mF("yt-remote-cast2-receiver-selected",function(){n8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),m8.push(g.mF("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),m8.push(g.mF("yt-remote-cast2-session-change",xGa)),m8.push(g.mF("yt-remote-connection-change",function(a){a?K7(k8(),"YouTube TV"):o8()||(K7(null,null),dGa())})),a=p8(),b.isAuto&&(a.id+="#dial"),g.yF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),l8(" -- with channel params: "+
g.Zg(a)),yGa(a),c.start(),k8()||zGa())},CGa=function(){var a=BGa();
H7()&&g.yI("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},BGa=function(){var a=j8().kd.$_gos();
var b=q8();b&&r8()&&(l6(a,b)||a.push(b));return DEa(a)},s8=function(){var a=DGa();
!a&&H7()&&cGa()&&(a={key:"cast-selector-receiver",name:cGa()});return a},DGa=function(){var a=BGa(),b=q8();
b||(b=o8());return g.Sa(a,function(a){return b&&h6(b,a.key)?!0:!1})},q8=function(){var a=k8();
if(!a)return null;var b=j8().Ae();return m6(b,a)},xGa=function(a){l8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=q8();b&&b.id==a.id?K7(b.id,"YouTube TV"):(b&&t8(),u8(a,1))}else r8()&&t8()},t8=function(){I7()?F7().stopSession():D7("stopSession called before API ready.");
var a=r8();a&&(a.disconnect(1),v8(null))},w8=function(){var a=r8();
return!!a&&3!=a.getProxyState()},l8=function(a){c7("remote",a)},j8=function(){if(!x8){var a=g.x("yt.mdx.remote.screenService_");
x8=a?new g8(a):null}return x8},k8=function(){return g.x("yt.mdx.remote.currentScreenId_")},EGa=function(a){g.Da("yt.mdx.remote.currentScreenId_",a,void 0)},FGa=function(){return g.x("yt.mdx.remote.connectData_")},n8=function(a){g.Da("yt.mdx.remote.connectData_",a,void 0)},r8=function(){return g.x("yt.mdx.remote.connection_")},v8=function(a){var b=r8();
n8(null);a||EGa("");g.Da("yt.mdx.remote.connection_",a,void 0);i8&&((0,g.C)(i8,function(b){b(a)}),i8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},o8=function(){var a=g.AI();
if(!a)return null;var b=j8().Ae();return m6(b,a)},u8=function(a,b){q8()&&q8();
EGa(a.id);var c=new $7(h8,a,p8());c.connect(b,FGa());c.subscribe("beforeDisconnect",function(a){e6("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){r8()&&v8(null)});
v8(c)},zGa=function(){var a=o8();
a?(l8("Resume connection to: "+i6(a)),u8(a,0)):(r6(),dGa(),l8("Skipping connecting because no session screen found."))},wGa=function(){var a=p8();
if(g.cc(a)){a=p6();var b=g.yI("yt-remote-session-name")||"",c=g.yI("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Da("yt.mdx.remote.channelParams_",a,void 0)}},p8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},yGa=function(a){a?(g.xI("yt-remote-session-app",a.app),g.xI("yt-remote-session-name",a.name)):(g.zI("yt-remote-session-app"),g.zI("yt-remote-session-name"));
g.Da("yt.mdx.remote.channelParams_",a,void 0)},y8=function(a,b,c){g.J.call(this);
this.D=a;this.A=b;this.C=new g.iH(this);g.K(this,this.C);this.C.R(b,"onCaptionsTrackListChanged",this.aS);this.C.R(b,"captionschanged",this.KQ);this.C.R(b,"captionssettingschanged",this.AG);this.C.R(b,"videoplayerreset",this.Pq);this.C.R(b,"mdxautoplaycancel",this.hK);this.O=this.C.R(b,"onVolumeChange",this.ME);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.bF,this);c.subscribe("remotePlayerChange",this.Hn,this);c.subscribe("remoteQueueChange",this.Pq,this);c.subscribe("autoplayUpNext",this.yE,
this);c.subscribe("previousNextChange",this.YE,this);c.subscribe("nowAutoplaying",this.QE,this);c.subscribe("autoplayDismissed",this.xE,this);this.suggestion=null;this.I=new g.JQ(64);this.B=new g.U(this.xG,500,this);g.K(this,this.B);this.F=new g.U(this.yG,1E3,this);g.K(this,this.F);this.L=new x6(this.mW,0,this);g.K(this,this.L);this.G={};this.M=new g.U(this.ZG,1E3,this);g.K(this,this.M);this.K=new g.lm(this.IO,1E3,this);g.K(this,this.K);this.V=g.y;this.AG();this.Pq();this.Hn()},z8=function(a,b){a.D.Je(b,
a.A.getVideoData().lengthSeconds)},GGa=function(a){z8(a,0);
a.B.stop();A8(a,new g.JQ(64))},C8=function(a,b){if(B8(a)&&!a.H){var c=null;
b&&(c={style:a.A.getSubtitlesUserSettings()},g.kc(c,b));a.o.lG(a.A.getVideoData(1).videoId,c);a.G=U7(a.o).o}},D8=function(a,b){var c=a.A.getPlaylist();
if(c){var d=c.ze();var e=c.listId.toString()}c=a.A.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.lk,vEa(c));A8(a,new g.JQ(1))},HGa=function(a,b){if(b){var c=a.A.getOption("captions","tracklist",{I4:1});
c&&c.length?(a.A.setOption("captions","track",b),a.H=!1):(a.A.loadModule("captions"),a.H=!0)}else a.A.setOption("captions","track",{})},B8=function(a){return U7(a.o).videoId==a.A.getVideoData(1).videoId},A8=function(a,b){a.F.stop();
var c=a.I;if(!g.PQ(c,b)){var d=g.X(b,2);d!=g.X(a.I,2)&&g.TU(a.A,d);a.I=b;IGa(a.D,c,b)}},E8=function(a){g.W.call(this,{J:"div",
N:"ytp-remote",P:[{J:"div",N:"ytp-remote-display-status",P:[{J:"div",N:"ytp-remote-display-status-icon",P:[g.Vsa()]},{J:"div",N:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.B=new g.KV(this,250);g.K(this,this.B);this.D=a;this.R(a,"presentingplayerstatechange",this.F);JGa(this,g.PU(a))},JGa=function(a,b){if(3==a.D.getPresentingPlayerType()){var c={RECEIVER_NAME:a.D.getOption("remote","currentReceiver").name};
c=g.X(b,128)?g.CV("\u5728$RECEIVER_NAME\u4e0a\u51fa\u73b0\u9519\u8bef",c):b.sb()||g.X(b,4)?g.CV("\u6b63\u5728$RECEIVER_NAME\u4e0a\u64ad\u653e",c):g.CV("\u5df2\u8fde\u63a5\u5230$RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},F8=function(a,b){g.aX.call(this,"\u64ad\u653e\u8bbe\u5907",0,a,b);
this.B=a;this.I={};this.R(a,"onMdxReceiversChange",this.M);this.R(a,"presentingplayerstatechange",this.M);this.M()},G8=function(a){g.mV.call(this,a);
this.A={key:k6(),name:"\u6b64\u8ba1\u7b97\u673a"};this.B=null;this.D=[];this.G=this.o=null;this.F=[this.A];this.C=this.A;this.qn=new g.JQ(64);this.I=0;this.H=-1;if(!g.VN(g.Y(this.player))){a=this.player;var b=g.yQ(a);b&&(b=b.un())&&(b=new F8(a,b),g.K(this,b));b=new E8(a);g.K(this,b);g.dV(a,b.element,4)}},IGa=function(a,b,c){a.qn=c;
a.player.U("presentingplayerstatechange",new g.TQ(c,b))},H8=function(a,b){if(b.key!=a.C.key)if(b.key==a.A.key)t8();
else{a.C=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Aa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.lk,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=vEa(d))&&(c.locationInfo=d);d=c}else d=null;l8("Connecting to: "+g.Zg(b));"cast-selector-receiver"==b.key?
(n8(d||null),I7()?F7().setLaunchParams(d||null):D7("setLaunchParams called before ready.")):!d&&w8()&&k8()==b.key?e6("yt-remote-connection-change",!0):(t8(),n8(d||null),d=j8().Ae(),(d=m6(d,b.key))&&u8(d,1))}},YEa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},H6={"'":"\\'"},KGa={},zEa={iY:"atp",M2:"ska",a2:"que",l1:"mus",I2:"sus",u_:"dsp",s2:"seq"};
f6.prototype.qh=function(){var a=new f6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.C=this.C;a.A=this.A;a.o=this.o};
var s6,o6="",w6=t6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",QEa=t6("loadCastFramework")||t6("loadCastApplicationFramework"),$Fa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(x6,g.J);g.h=x6.prototype;g.h.gL=function(a){this.B=arguments;this.o=!1;this.Fa?this.C=(0,g.H)()+this.Gd:this.Fa=g.Ug(this.D,this.Gd)};
g.h.stop=function(){this.Fa&&(g.Vg(this.Fa),this.Fa=null);this.C=null;this.o=!1;this.B=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.h.W=function(){this.stop();x6.fa.W.call(this)};
g.h.hL=function(){this.C?(this.Fa=g.Ug(this.D,this.C-(0,g.H)()),this.C=null):(this.Fa=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=z6.prototype;g.h.Gi=null;g.h.Hf=!1;g.h.zl=null;g.h.Gy=null;g.h.Vk=null;g.h.ak=null;g.h.Ah=null;g.h.Zh=null;g.h.ij=null;g.h.Uc=null;g.h.co=0;g.h.Jf=null;g.h.ks=null;g.h.Bh=null;g.h.Km=-1;g.h.XF=!0;g.h.ni=!1;g.h.Nu=0;g.h.jr=null;var WEa={},C6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.jV=function(a){a=a.target;var b=this.jr;b&&3==g.yy(a)?b.Gm():this.iH(a)};
g.h.iH=function(a){try{if(a==this.Uc)a:{var b=g.yy(this.Uc),c=this.Uc.A,d=this.Uc.getStatus();if(g.ce&&!g.Mc(10)||g.ee&&!g.Lc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Jf&&!g.Cy(this.Uc))break a;this.ni||4!=b||7==c||(8==c||0>=d?this.o.Bf(3):this.o.Bf(2));J6(this);var e=this.Uc.getStatus();this.Km=e;var f=g.Cy(this.Uc);(this.Hf=200==e)?(4==b&&F6(this),this.D?(XEa(this,b,f),g.Jf&&this.Hf&&3==b&&(this.Z.X(this.A,"tick",this.eV),this.A.start())):E6(this,f),this.Hf&&!this.ni&&(4==b?this.o.Nq(this):
(this.Hf=!1,B6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Bh=3,D6(13)):(this.Bh=0,D6(14)),F6(this),G6(this))}}catch(k){this.Uc&&g.Cy(this.Uc)}finally{}};
g.h.eV=function(){var a=g.yy(this.Uc),b=g.Cy(this.Uc);this.co<b.length&&(J6(this),XEa(this,a,b),this.Hf&&4!=a&&B6(this))};
g.h.qU=function(a){I6((0,g.A)(this.pU,this,a),0)};
g.h.pU=function(a){this.ni||(J6(this),E6(this,a),B6(this))};
g.h.jF=function(a){I6((0,g.A)(this.oU,this,a),0)};
g.h.oU=function(a){this.ni||(F6(this),this.Hf=a,this.o.Nq(this),this.o.Bf(4))};
g.h.cancel=function(){this.ni=!0;F6(this)};
g.h.FU=function(){this.zl=null;var a=(0,g.H)();0<=a-this.Gy?(2!=this.ak&&this.o.Bf(3),F6(this),this.Bh=2,D6(18),G6(this)):$Ea(this,this.Gy-a)};
g.h.getLastError=function(){return this.Bh};g.h=cFa.prototype;g.h.Lu=null;g.h.pe=null;g.h.kr=!1;g.h.UB=null;g.h.np=null;g.h.Qv=null;g.h.Mu=null;g.h.Ye=null;g.h.Rg=-1;g.h.Jm=null;g.h.Rl=null;g.h.connect=function(a){this.Mu=a;a=L6(this.o,null,this.Mu);D6(3);this.UB=(0,g.H)();var b=this.o.H;null!=b?(this.Jm=b[0],(this.Rl=b[1])?(this.Ye=1,dFa(this)):(this.Ye=2,N6(this))):(d6(a,"MODE","init"),this.pe=new z6(this,void 0,void 0,void 0),this.pe.Gi=this.Lu,A6(this.pe,a,!1,null,!0),this.Ye=0)};
g.h.iK=function(a){if(a)this.Ye=2,N6(this);else{D6(4);var b=this.o;b.Vf=b.ph.Rg;U6(b,9)}a&&this.Bf(2)};
g.h.fu=function(a){return this.o.fu(a)};
g.h.abort=function(){this.pe&&(this.pe.cancel(),this.pe=null);this.Rg=-1};
g.h.TB=function(){return!1};
g.h.cF=function(a,b){this.Rg=a.Km;if(0==this.Ye)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Vf=this.Rg;U6(c,2);return}this.Jm=c[0];this.Rl=c[1]}else c=this.o,c.Vf=this.Rg,U6(c,2);else if(2==this.Ye)if(this.kr)D6(7),this.Qv=(0,g.H)();else if("11111"==b){if(D6(6),this.kr=!0,this.np=(0,g.H)(),c=this.np-this.UB,!g.ce||g.Mc(10)||500>c)this.Rg=200,this.pe.cancel(),D6(12),M6(this.o,this,!0)}else D6(8),this.np=this.Qv=(0,g.H)(),this.kr=!1};
g.h.Nq=function(){this.Rg=this.pe.Km;if(this.pe.Hf)0==this.Ye?this.Rl?(this.Ye=1,dFa(this)):(this.Ye=2,N6(this)):2==this.Ye&&((!g.ce||g.Mc(10)?!this.kr:200>this.Qv-this.np)?(D6(11),M6(this.o,this,!1)):(D6(12),M6(this.o,this,!0)));else{0==this.Ye?D6(9):2==this.Ye&&D6(10);var a=this.o;this.pe.getLastError();a.Vf=this.Rg;U6(a,2)}};
g.h.Un=function(){return this.o.Un()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Bf=function(a){this.o.Bf(a)};g.h=O6.prototype;g.h.km=null;g.h.je=null;g.h.zc=null;g.h.Ku=null;g.h.qp=null;g.h.kA=null;g.h.Fp=null;g.h.Bn=0;g.h.cQ=0;g.h.Fd=null;g.h.uh=null;g.h.Eg=null;g.h.ti=null;g.h.ph=null;g.h.es=null;g.h.vk=-1;g.h.LC=-1;g.h.Vf=-1;g.h.Rj=0;g.h.Hj=0;g.h.ri=8;var V6=new g.ig;g.B(fFa,g.Hf);g.B(gFa,g.Hf);g.B(hFa,g.Hf);g.h=O6.prototype;g.h.connect=function(a,b,c,d,e){D6(0);this.Ku=b;this.km=c||{};d&&g.Aa(e)&&(this.km.OSID=d,this.km.OAID=e);this.F?(I6((0,g.A)(this.DA,this,a),100),lFa(this)):this.DA(a)};
g.h.DA=function(a){this.ph=new cFa(this);this.ph.Lu=null;this.ph.A=this.D;this.ph.connect(a)};
g.h.TB=function(){return 0==this.o};
g.h.iF=function(a){this.uh=null;oFa(this,a)};
g.h.hF=function(){this.Eg=null;this.zc=new z6(this,this.C,"rpc",this.G);this.zc.Gi=null;this.zc.Nu=0;var a=this.kA.clone();g.Rn(a,"RID","rpc");g.Rn(a,"SID",this.C);g.Rn(a,"CI",this.es?"0":"1");g.Rn(a,"AID",this.vk);P6(this,a);if(!g.ce||g.Mc(10))g.Rn(a,"TYPE","xmlhttp"),A6(this.zc,a,!0,this.Fp,!1);else{g.Rn(a,"TYPE","html");var b=this.zc,c=!!this.Fp;b.ak=3;b.Ah=c6(a.clone());ZEa(b,c)}};
g.h.cF=function(a,b){if(0!=this.o&&(this.zc==a||this.je==a))if(this.Vf=a.Km,this.je==a&&3==this.o)if(7<this.ri){try{var c=this.D.parse(b)}catch(f){c=null}if(g.Ga(c)&&3==c.length)if(0==c[0])a:{if(!this.Eg){if(this.zc)if(this.zc.Vk+3E3<this.je.Vk)R6(this),this.zc.cancel(),this.zc=null;else break a;T6(this);D6(19)}}else this.LC=c[1],0<this.LC-this.vk&&37500>c[2]&&this.es&&0==this.Hj&&!this.ti&&(this.ti=I6((0,g.A)(this.FQ,this),6E3));else U6(this,11)}else b!=KGa.lZ.o&&U6(this,11);else if(this.zc==a&&
R6(this),!g.D(b)){c=this.D.parse(b);g.Ga(c);for(var d=0;d<c.length;d++){var e=c[d];this.vk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.C=e[1],this.Fp=e[2],e=e[3],null!=e?this.ri=e:this.ri=6,this.o=3,this.Fd&&this.Fd.xA(),this.kA=L6(this,this.Un()?this.Fp:null,this.Ku),pFa(this)):"stop"==e[0]&&U6(this,7):3==this.o&&("stop"==e[0]?U6(this,7):"noop"!=e[0]&&this.Fd&&this.Fd.wA(e),this.Hj=0)}}};
g.h.FQ=function(){null!=this.ti&&(this.ti=null,this.zc.cancel(),this.zc=null,T6(this),D6(20))};
g.h.Nq=function(a){if(this.zc==a){R6(this);this.zc=null;var b=2}else if(this.je==a)this.je=null,b=1;else return;this.Vf=a.Km;if(0!=this.o)if(a.Hf)1==b?(b=(0,g.H)()-a.Vk,V6.dispatchEvent(new gFa(V6,a.ij?a.ij.length:0,b,this.Rj)),Q6(this),this.B.length=0):pFa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Vf)){if(d=1==b)this.je||this.uh||1==this.o||2<=this.Rj?d=!1:(this.uh=I6((0,g.A)(this.iF,this,a),qFa(this,this.Rj)),this.Rj++,d=!0);d=!(d||2==b&&T6(this))}if(d)switch(c){case 1:U6(this,
5);break;case 4:U6(this,10);break;case 3:U6(this,6);break;case 7:U6(this,12);break;default:U6(this,2)}}};
g.h.FK=function(a){if(!g.Wa(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.cW=function(a){a?D6(2):(D6(1),rFa(this,8))};
g.h.fu=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.ry;a.H=!1;return a};
g.h.isActive=function(){return!!this.Fd&&this.Fd.isActive(this)};
g.h.Bf=function(a){V6.dispatchEvent(new hFa(V6,a))};
g.h.Un=function(){return!(!g.ce||g.Mc(10))};
g.h=sFa.prototype;g.h.xA=function(){};
g.h.wA=function(){};
g.h.vA=function(){};
g.h.Qt=function(){};
g.h.yB=function(){return{}};
g.h.isActive=function(){return!0};g.B(W6,g.J);g.h=W6.prototype;g.h.gU=function(){this.Gd=Math.min(3E5,2*this.Gd);this.C();this.A&&this.start()};
g.h.start=function(){var a=this.Gd+15E3*Math.random();g.qv(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Gd=5E3};g.B(X6,sFa);g.h=X6.prototype;g.h.subscribe=function(a,b,c){return this.C.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.C.unsubscribe(a,b,c)};
g.h.Ak=function(a){return this.C.Hi(a)};
g.h.U=function(a,b){return this.C.U.apply(this.C,arguments)};
g.h.dispose=function(){this.Bb||(this.Bb=!0,g.Ff(this.C),vFa(this),g.Ff(this.A),this.A=null)};
g.h.la=function(){return this.Bb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.I="";this.A.stop();this.D=a||null;this.B=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new O6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.o;e&&(e.Fd=null);d.Fd=this;this.o=d;e?this.o.connect(a,b,this.F,e.C,e.vk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.kc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):Y6(this)&&mFa(this.o,c)};
g.h.xA=function(){this.A.reset();this.D=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)mFa(this.o,a[b])}this.U("handlerOpened")};
g.h.vA=function(a){var b=2==a&&401==this.o.Vf;4==a||b||this.A.start();this.U("handlerError",a)};
g.h.Qt=function(a){if(!this.A.isActive())this.U("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.yB=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.B&&(a.ui=""+this.B);0!=this.H&&(a.ui=""+this.H);this.D&&g.kc(a,this.D);return a};
g.h.wA=function(a){"S"==a[0]?this.I=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),kFa(this.o)):this.U("handlerMessage",new tFa(a[0],a[1]))};
g.h.FW=function(){this.A.isActive();var a=this.o,b=0;a.zc&&b++;a.je&&b++;0!=b||this.connect(this.D,this.B)};Z6.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z6.prototype.C=function(a,b){a(Error("Request error: "+b.status))};
Z6.prototype.D=function(a){a(Error("request timed out"))};var DFa=(0,g.H)(),b7=null,e7=Array(50),d7=-1,f7=!1;g.B(g7,g.V);g7.prototype.Ae=function(){return this.o};
g7.prototype.contains=function(a){return!!l6(this.o,a)};
g7.prototype.get=function(a){return a?m6(this.o,a):null};
g7.prototype.info=function(a){c7(this.G,a)};g.B(h7,g.V);var LGa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=h7.prototype;g.h.start=function(){!this.o&&isNaN(this.Fa)&&this.kH()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Fa)||(g.hF(this.Fa),this.Fa=NaN)};
g.h.W=function(){this.stop();h7.fa.W.call(this)};
g.h.kH=function(){this.Fa=NaN;this.o=g.TF($6(this.F,"/pairing/get_screen"),{method:"POST",Rb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.HW,this),onError:(0,g.A)(this.GW,this),Kd:(0,g.A)(this.IW,this)})};
g.h.HW=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.C;c.name=this.B;this.U("pairingComplete",new g6(c))};
g.h.GW=function(a){this.o=null;a.status&&404==a.status?this.A>=LGa.length?this.U("pairingFailed",Error("DIAL polling timed out")):(a=LGa[this.A],this.Fa=g.fF((0,g.A)(this.kH,this),a),this.A++):this.U("pairingFailed",Error("Server error "+a.status))};
g.h.IW=function(){this.o=null;this.U("pairingFailed",Error("Server not responding"))};g.B(j7,g7);g.h=j7.prototype;g.h.start=function(){i7(this)&&this.U("screenChange");!g.yI("yt-remote-lounge-token-expiration")&&HFa(this);g.hF(this.A);this.A=g.fF((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){i7(this);EFa(this,a);k7(this,!1);this.U("screenChange");b(a);a.token||HFa(this)};
g.h.remove=function(a,b){var c=i7(this);GFa(this,a)&&(k7(this,!1),c=!0);b(a);c&&this.U("screenChange")};
g.h.Xr=function(a,b,c,d){var e=i7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.U("screenChange")};
g.h.W=function(){g.hF(this.A);j7.fa.W.call(this)};
g.h.vL=function(a){i7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k7(this,!b);b&&c7(this.G,"Missed "+b+" lounge tokens.")};
g.h.uL=function(a){c7(this.G,"Requesting lounge tokens failed: "+a)};g.B(m7,g.V);g.h=m7.prototype;g.h.start=function(){var a=parseInt(g.yI("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.H)()-144E5<a?0:a)?o7(this):(this.B=(0,g.H)()+3E5,g.xI("yt-remote-fast-check-period",this.B),this.zx())};
g.h.isEmpty=function(){return g.cc(this.o)};
g.h.update=function(){l7("Updating availability on schedule.");var a=this.F(),b=g.Nb(this.o,function(b,d){return b&&!!m6(a,d)},this);
n7(this,b)};
g.h.W=function(){g.hF(this.C);this.C=NaN;this.A&&(this.A.abort(),this.A=null);m7.fa.W.call(this)};
g.h.zx=function(){g.hF(this.C);this.C=NaN;this.A&&this.A.abort();var a=KFa(this);if(g.Rb(a)){var b=$6(this.D,"/pairing/get_screen_availability");this.A=a7(this.D,b,{lounge_token:g.Ub(a).join(",")},(0,g.A)(this.IT,this,a),(0,g.A)(this.HT,this))}else n7(this,{}),o7(this)};
g.h.IT=function(a,b){this.A=null;var c=g.Ub(KFa(this));if(g.sb(c,g.Ub(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;n7(this,d);o7(this)}else this.qc("Changing Screen set during request."),this.zx()};
g.h.HT=function(a){this.qc("Screen availability failed: "+a);this.A=null;o7(this)};
g.h.qc=function(a){c7("OnlineScreenService",a)};g.B(p7,g7);g.h=p7.prototype;g.h.start=function(){this.C.start();this.A.start();this.o.length&&(this.U("screenChange"),this.A.isEmpty()||this.U("onlineScreenChange"))};
g.h.add=function(a,b,c){this.C.add(a,b,c)};
g.h.remove=function(a,b,c){this.C.remove(a,b,c);this.A.update()};
g.h.Xr=function(a,b,c,d){this.C.contains(a)?this.C.Xr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c7(this.G,a),d(Error(a)))};
g.h.Ae=function(a){return a?this.o:g.db(this.o,(0,g.qe)(this.B,function(a){return!this.contains(a)},this))};
g.h.lH=function(){return(0,g.qe)(this.Ae(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.mH=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new h7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.Ff(f);d(q7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ff(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.KW=function(a,b,c,d){g.TF($6(this.F,"/pairing/get_screen"),{method:"POST",Rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new g6(d.screen||{});if(!e.name||OFa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);OFa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(q7(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Kd:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.Ff(this.C);g.Ff(this.A);p7.fa.W.call(this)};
g.h.JL=function(){PFa(this);this.U("screenChange");this.A.update()};
p7.prototype.dispose=p7.prototype.dispose;g.B(s7,g.V);g.h=s7.prototype;g.h.Oq=function(a){this.C=a;this.U("sessionScreen",this.C)};
g.h.Fe=function(a){this.la()||(a&&t7(this,""+a),this.C=null,this.U("sessionScreen",null))};
g.h.info=function(a){c7(this.M,a)};
g.h.oH=function(){return null};
g.h.Mx=function(a){var b=this.A;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){t7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.Mx("");s7.fa.W.call(this)};g.B(u7,s7);g.h=u7.prototype;g.h.Lx=function(a){if(this.o){if(this.o==a)return;t7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);RFa(this)};
g.h.xk=function(a){this.info("launchWithParams no-op for Cast: "+g.Zg(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.Fe()},this),(0,g.A)(function(){this.Fe(Error("Failed to stop receiver app."))},this)):this.Fe(Error("Stopping cast device witout session."))};
g.h.Mx=g.y;g.h.W=function(){this.info("disposeInternal");g.hF(this.B);this.B=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;u7.fa.W.call(this)};
g.h.RU=function(a,b){if(!this.la())if(b){var c=g.my(b);if(g.Ja(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Zg(c));switch(d){case "mdxSessionStatus":QFa(this,c.screenId);break;default:t7(this,"Unknown youtube message: "+d)}}else t7(this,"Unable to parse message.")}else t7(this,"No data in message.")};
g.h.JB=function(a,b,c,d){NFa(this.I,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(t7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.fF((0,g.A)(this.JB,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.oH=function(){return this.o};
g.h.LW=function(a){this.la()||a||(t7(this,"Cast session died."),this.Fe())};g.B(v7,s7);g.h=v7.prototype;g.h.Lx=function(a){this.B=a;this.B.addUpdateListener(this.L)};
g.h.xk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.y;g.hF(this.F);this.B?this.B.stop((0,g.A)(this.Fe,this,null),(0,g.A)(this.Fe,this,"Failed to stop DIAL device.")):this.Fe()};
g.h.W=function(){this.o();this.o=g.y;g.hF(this.F);this.B&&this.B.removeUpdateListener(this.L);this.B=null;v7.fa.W.call(this)};
g.h.OW=function(a){this.la()||a||(t7(this,"DIAL session died."),this.o(),this.o=g.y,this.Fe())};
g.h.tv=function(a){this.K=k6();if(this.D){var b=new chrome.cast.DialLaunchResponse(!0,TFa(this));a(b);SFa(this)}else this.G=(0,g.A)(function(){g.hF(this.F);this.G=g.y;this.F=NaN;var b=new chrome.cast.DialLaunchResponse(!0,TFa(this));a(b);SFa(this)},this),this.F=g.fF((0,g.A)(function(){this.G()},this),100)};
g.h.UM=function(a,b,c){NFa(this.I,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(a){a&&a.token?(this.Oq(a),b(new chrome.cast.DialLaunchResponse(!1))):this.tv(b,c)},this),(0,g.A)(function(a){t7(this,"Failed to get DIAL screen: "+a);
this.tv(b,c)},this))};g.B(w7,s7);w7.prototype.stop=function(){this.Fe()};
w7.prototype.Lx=g.y;w7.prototype.xk=function(){g.hF(this.o);this.o=NaN;var a=m6(this.I.Ae(),this.A.label);a?this.Oq(a):this.Fe(Error("No such screen"))};
w7.prototype.W=function(){g.hF(this.o);this.o=NaN;w7.fa.W.call(this)};g.B(x7,g.V);g.h=x7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.A)(this.eF,this),(0,g.A)(this.qT,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.nR,this);chrome.cast.initialize(c,(0,g.A)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.B),AFa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.nH,this)),this.C=VFa(this),chrome.cast.setCustomReceivers(this.C,g.y,(0,g.A)(function(a){this.qc("Failed to set initial custom receivers: "+g.Zg(a))},this)),this.U("yt-remote-cast2-availability-change",z7(this)),b(!0))},this),(0,g.A)(function(a){this.qc("Failed to initialize API: "+g.Zg(a));
b(!1)},this))};
g.h.KV=function(a,b){y7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.C;if(!a||c&&c.id!=a)y7("Unsetting old screen status: "+this.o.A.friendlyName),A7(this,null)}if(a&&b){if(!this.o){c=m6(this.A.Ae(),a);if(!c){y7("setConnectedScreenStatus: Unknown screen.");return}var d=UFa(this,c);d||(y7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.C.push(d),chrome.cast.setCustomReceivers(this.C,
g.y,(0,g.A)(function(a){this.qc("Failed to set initial custom receivers: "+g.Zg(a))},this)));
y7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);A7(this,new w7(this.A,d),!0)}this.o.Mx(b)}else y7("setConnectedScreenStatus: no screen.")};
g.h.LV=function(a){this.la()?this.qc("Setting connection data on disposed cast v2"):this.o?this.o.xk(a):this.qc("Setting connection data without a session")};
g.h.NW=function(){this.la()?this.qc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),A7(this,null)):y7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.A)(this.eF,this),(0,g.A)(this.NT,this))};
g.h.W=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.nH,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);g.ab(g.x("yt.mdx.remote.debug.handlers_")||[],xFa);g.Ff(this.o);x7.fa.W.call(this)};
g.h.qc=function(a){c7("Controller",a)};
g.h.fF=function(a,b){this.o==a&&(b||A7(this,null),this.U("yt-remote-cast2-session-change",b))};
g.h.mT=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),y7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)y7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{y7("onReceiverAction_: Casting to active receiver.");this.o.C&&this.U("yt-remote-cast2-session-change",this.o.C);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:A7(this,
new w7(this.A,a));break;case chrome.cast.ReceiverType.DIAL:A7(this,new v7(this.A,a,this.F));break;case chrome.cast.ReceiverType.CAST:A7(this,new u7(this.A,a));break;default:this.qc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.qc("Stopping receiver w/o session: "+a.friendlyName)}else this.qc("onReceiverAction_ called without receiver.")};
g.h.nR=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.qc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.qc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.C)return y7("Reselecting dial screen."),
this.U("yt-remote-cast2-session-change",this.o.C),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.qc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);A7(this,new v7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.A)(b.UM,b,(b.H.extraData||{}).screenId||null)):new Promise((0,g.A)(b.tv,b))};
g.h.eF=function(a){if(!this.la()){y7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)y7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),A7(this,new u7(this.A,b),!0);else{this.qc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=m6(this.A.Ae(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(y7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ff(this.o),this.o=new u7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.fF,this,this.o)),this.o.xk(null));this.o.Lx(a)}}};
g.h.MW=function(){return this.o?this.o.oH():null};
g.h.NT=function(a){this.la()||(this.qc("Failed to estabilish a session: "+g.Zg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&A7(this,null))};
g.h.qT=function(a){y7("Receiver availability updated: "+a);if(!this.la()){var b=z7(this);this.D=a==chrome.cast.ReceiverAvailability.AVAILABLE;z7(this)!=b&&this.U("yt-remote-cast2-availability-change",z7(this))}};
g.h.nH=function(){this.la()||(this.C=VFa(this),y7("Updating custom receivers: "+g.Zg(this.C)),chrome.cast.setCustomReceivers(this.C,g.y,(0,g.A)(function(){this.qc("Failed to set custom receivers.")},this)),this.U("yt-remote-cast2-availability-change",z7(this)))};
x7.prototype.setLaunchParams=x7.prototype.LV;x7.prototype.setConnectedScreenStatus=x7.prototype.KV;x7.prototype.stopSession=x7.prototype.NW;x7.prototype.getCastSession=x7.prototype.MW;x7.prototype.requestSession=x7.prototype.requestSession;x7.prototype.init=x7.prototype.init;x7.prototype.dispose=x7.prototype.dispose;var G7=[];g.h=L7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";M7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Zf=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.B=a.seekableStart,this.A=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.C=a.liveIngestionTime,this.D=!isNaN(this.C))};
g.h.sb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.D?this.H+N7(this):this.H};
g.h.clone=function(){return new L7(R7(this))};g.B(T7,g.V);g.h=T7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.y,Z7(this,"play")):Y7(this,"play"),X7(this,1,P7(U7(this))),this.U("remotePlayerChange")):V7(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.y,Z7(this,"pause")):Y7(this,"pause"),X7(this,2,P7(U7(this))),this.U("remotePlayerChange")):V7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.A){var b=U7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.sb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.y,Z7(this,"seekTo",{newTime:a}))}else Y7(this,"seekTo",{newTime:a});X7(this,3,a);this.U("remotePlayerChange")}else V7(this,g.Ma(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.y,Z7(this,"stopVideo")):Y7(this,"stopVideo");var a=U7(this);a.index=-1;a.videoId="";M7(a);W7(this,a);this.U("remotePlayerChange")}else V7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=U7(this);if(this.C){if(c.volume!=a){var d=Math.round(a)/100;this.C.setReceiverVolumeLevel(d,(0,g.A)(function(){c7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.qc("failed to set receiver volume.")},this))}c.muted!=b&&this.C.setReceiverMuted(b,(0,g.A)(function(){c7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.qc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Y7(this,"setVolume",e)}c.muted=b;c.volume=a;W7(this,c)}else V7(this,g.Ma(this.setVolume,a,b))};
g.h.lG=function(a,b){if(1==this.o){var c=U7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Zg(b.style),g.kc(d,c.o));Y7(this,"setSubtitlesTrack",d);W7(this,c)}else V7(this,g.Ma(this.lG,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){Y7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Pb.id});var c=U7(this);c.audioTrackId=b.Pb.id;W7(this,c)}else V7(this,g.Ma(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=U7(this);c=c||0;var m={videoId:a,currentIndex:c};Q7(l,a,c);g.Aa(b)&&(O7(l,b),m.currentTime=b);g.Aa(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Zg(k));Y7(this,"setPlaylist",m);d||W7(this,l)};
g.h.Vq=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"previous")}else V7(this,g.Ma(this.Vq,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"next")}else V7(this,g.Ma(this.nextVideo,a,b))};
g.h.XA=function(){1==this.o?Y7(this,"dismissAutoplay"):V7(this,this.XA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.U("proxyStateChange",a,this.o)}T7.fa.dispose.call(this)};
g.h.W=function(){hGa(this);this.B=null;this.D.clear();S7(this,null);T7.fa.W.call(this)};
g.h.Oy=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.FD(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.iT=function(a,b){this.U(a,b)};
g.h.MQ=function(a){if(!a)this.En(null),S7(this,null);else if(this.C.receiver.volume){a=this.C.receiver.volume;var b=U7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,W7(this,b)}};
g.h.En=function(a){c7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),iGa(this),this.U("remotePlayerChange")};
g.h.LQ=function(a){a?(iGa(this),this.U("remotePlayerChange")):this.En(null)};
g.h.ey=function(){Y7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.YQ=function(){var a=eGa();a&&S7(this,a)};
g.h.qc=function(a){c7("CP",a)};g.B($7,g.V);g.h=$7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Aa(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Aa(k)&&(l.currentIndex=k);c&&(this.ob.listId=c);this.ob.videoId=d;this.ob.index=k||0;this.ob.state=3;O7(this.ob,m);this.B="UNSUPPORTED";a8("Connecting with setPlaylist and params: "+g.Zg(l));this.o.connect({method:"setPlaylist",
params:g.Zg(l)},a,HEa())}else a8("Connecting without params"),this.o.connect({},a,HEa());kGa(this)};
g.h.dispose=function(){this.la()||(this.U("beforeDispose"),b8(this,3));$7.fa.dispose.call(this)};
g.h.W=function(){c8(this);e8(this);d8(this);g.hF(this.I);this.I=NaN;g.hF(this.K);this.K=NaN;this.C=null;g.WG(this.O);this.O.length=0;this.o.dispose();$7.fa.W.call(this);this.B=this.G=this.A=this.ob=this.o=null};
g.h.lL=function(){this.F(2)};
g.h.QQ=function(){a8("Channel opened");this.V&&(this.V=!1,d8(this),this.M=g.fF((0,g.A)(function(){a8("Timing out waiting for a screen.");this.F(1)},this),15E3));
LEa(uFa(this.o),this.aa)};
g.h.NQ=function(){a8("Channel closed");isNaN(this.D)?r6(!0):r6();this.dispose()};
g.h.OQ=function(a){r6();isNaN(this.H())?(a8("Channel error: "+a+" without reconnection"),this.dispose()):(this.V=!0,a8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),b8(this,2))};
g.h.PQ=function(a){a.params?a8("Received: action="+a.action+", params="+g.Zg(a.params)):a8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.my(a.params.devices);this.A=(0,g.I)(a,function(a){return new f6(a)});
a=!!g.Sa(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
nGa(this,a);break;case "loungeScreenDisconnected":g.bb(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
nGa(this,!1);break;case "remoteConnected":var b=new f6(g.my(a.params.device));g.Sa(this.A,function(a){return b?a.id==b.id:!1})||g.Za(this.A,b);
break;case "remoteDisconnected":b=new f6(g.my(a.params.device));g.bb(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":pGa(this,a);break;case "nowPlaying":rGa(this,a);break;case "onStateChange":qGa(this,a);break;case "onAdStateChange":sGa(this,a);break;case "onVolumeChanged":tGa(this,a);break;case "onSubtitlesTrackChanged":oGa(this,a);break;case "nowAutoplaying":uGa(this,a);break;case "autoplayDismissed":this.U("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.U("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.U("autoplayModeChange",this.B);"DISABLED"==this.B&&this.U("autoplayDismissed");break;case "onHasPreviousNextChanged":vGa(this,a);break;case "requestAssistedSignIn":this.U("assistedSignInRequested",a.params.authCode);break;default:a8("Unrecognized action: "+a.action)}};
g.h.rV=function(){if(this.C){var a=this.C;this.C=null;this.ob.videoId!=a&&f8(this,"getNowPlaying")}};
$7.prototype.subscribe=$7.prototype.subscribe;$7.prototype.unsubscribeByKey=$7.prototype.Ak;$7.prototype.ia=function(){var a=3;this.la()||(a=0,isNaN(this.H())?Y6(this.o)&&isNaN(this.D)&&(a=1):a=2);return a};
$7.prototype.getProxyState=$7.prototype.ia;$7.prototype.F=function(a){a8("Disconnecting with "+a);c8(this);this.U("beforeDisconnect",a);1==a&&r6();vFa(this.o,a);this.dispose()};
$7.prototype.disconnect=$7.prototype.F;$7.prototype.ea=function(){var a=this.ob;this.C&&(a=this.ob.clone(),Q7(a,this.C,a.index));return R7(a)};
$7.prototype.getPlayerContextData=$7.prototype.ea;
$7.prototype.ma=function(a){var b=new L7(a);b.videoId&&b.videoId!=this.ob.videoId&&(this.C=b.videoId,g.hF(this.I),this.I=g.fF((0,g.A)(this.rV,this),5E3));var c=[];this.ob.listId==b.listId&&this.ob.videoId==b.videoId&&this.ob.index==b.index||c.push("remoteQueueChange");this.ob.playerState==b.playerState&&this.ob.volume==b.volume&&this.ob.muted==b.muted&&P7(this.ob)==P7(b)&&g.Zg(this.ob.o)==g.Zg(b.o)||c.push("remotePlayerChange");this.ob.reset(a);(0,g.C)(c,function(a){this.U(a)},this)};
$7.prototype.setPlayerContextData=$7.prototype.ma;$7.prototype.Y=function(){var a=this.o.F.id,b=g.Sa(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
$7.prototype.getOtherConnectedRemoteId=$7.prototype.Y;$7.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():NaN};
$7.prototype.getReconnectTimeout=$7.prototype.H;$7.prototype.ba=function(){return this.B||"UNSUPPORTED"};
$7.prototype.getAutoplayMode=$7.prototype.ba;$7.prototype.ga=function(){return this.G||""};
$7.prototype.getAutoplayVideoId=$7.prototype.ga;$7.prototype.xa=function(){if(!isNaN(this.H())){var a=this.o.A;g.rv(a.o);a.start()}};
$7.prototype.reconnect=$7.prototype.xa;$7.prototype.ka=function(a,b){f8(this,a,b);mGa(this)};
$7.prototype.sendMessage=$7.prototype.ka;g.B(g8,g7);g.h=g8.prototype;g.h.Ae=function(a){return this.kd.$_gs(a)};
g.h.contains=function(a){return!!this.kd.$_c(a)};
g.h.get=function(a){return this.kd.$_g(a)};
g.h.start=function(){this.kd.$_st()};
g.h.add=function(a,b,c){this.kd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.kd.$_r(a,b,c)};
g.h.Xr=function(a,b,c,d){this.kd.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.A.length;a<b;++a)this.kd.$_ubk(this.A[a]);this.A.length=0;this.kd=null;g8.fa.W.call(this)};
g.h.JW=function(){this.U("screenChange")};
g.h.HS=function(){this.U("onlineScreenChange")};
p7.prototype.$_st=p7.prototype.start;p7.prototype.$_gspc=p7.prototype.KW;p7.prototype.$_gsppc=p7.prototype.mH;p7.prototype.$_c=p7.prototype.contains;p7.prototype.$_g=p7.prototype.get;p7.prototype.$_a=p7.prototype.add;p7.prototype.$_un=p7.prototype.Xr;p7.prototype.$_r=p7.prototype.remove;p7.prototype.$_gs=p7.prototype.Ae;p7.prototype.$_gos=p7.prototype.lH;p7.prototype.$_s=p7.prototype.subscribe;p7.prototype.$_ubk=p7.prototype.Ak;var h8=null,i8=null,x8=null,m8=[];g.r(y8,g.J);g.h=y8.prototype;
g.h.W=function(){g.J.prototype.W.call(this);this.B.stop();this.F.stop();this.L.stop();this.V();this.o.unsubscribe("proxyStateChange",this.bF,this);this.o.unsubscribe("remotePlayerChange",this.Hn,this);this.o.unsubscribe("remoteQueueChange",this.Pq,this);this.o.unsubscribe("autoplayUpNext",this.yE,this);this.o.unsubscribe("previousNextChange",this.YE,this);this.o.unsubscribe("nowAutoplaying",this.QE,this);this.o.unsubscribe("autoplayDismissed",this.xE,this);this.o=this.D=null};
g.h.zD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(B8(this)){if(!U7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":U7(this.o).sb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Gm(c[0],c[1]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();D8(this,0==c?void 0:c);break;case "control_seek":D8(this,c[0]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,c)}};
g.h.KQ=function(a){this.L.gL(a)};
g.h.mW=function(a){this.zD("control_subtitles_set_track",g.cc(a)?null:a)};
g.h.AG=function(){var a=this.A.getOption("captions","track");g.cc(a)||C8(this,a)};
g.h.ME=function(a){if(B8(this)){this.o.unsubscribe("remotePlayerChange",this.Hn,this);var b=Math.round(a.volume);a=!!a.muted;var c=U7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.Hn,this)}};
g.h.aS=function(){g.cc(this.G)||HGa(this,this.G);this.H=!1};
g.h.bF=function(a,b){this.F.stop();2==b&&this.yG()};
g.h.Hn=function(){if(B8(this)){this.B.stop();var a=U7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.Zk(1);break;case 1082:case 1083:this.D.Zk(0);break;default:this.D.Zk(-1)}switch(a.playerState){case 1081:case 1:A8(this,new g.JQ(8));this.xG();break;case 1085:case 3:A8(this,new g.JQ(9));break;case 1083:case 0:A8(this,new g.JQ(2));this.K.stop();z8(this,this.A.getVideoData().lengthSeconds);break;case 1084:A8(this,new g.JQ(4));break;case 2:A8(this,new g.JQ(4));z8(this,P7(a));
break;case -1:A8(this,new g.JQ(64));break;case -1E3:A8(this,new g.JQ(128,{errorCode:"mdx.remoteerror",message:"\u6b64\u89c6\u9891\u65e0\u6cd5\u8fdc\u7a0b\u64ad\u653e\u3002"}))}a=U7(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.G=a,HGa(this,a));a=U7(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.ZG()}else GGa(this)};
g.h.YE=function(){this.A.U("mdxpreviousnextchange")};
g.h.Pq=function(){B8(this)||GGa(this)};
g.h.hK=function(){this.o.XA()};
g.h.yE=function(a){a&&(a=g.TF("/watch_queue_ajax",{method:"GET",cd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.sU,this)}))&&(this.V=(0,g.A)(a.abort,a))};
g.h.sU=function(a,b){var c=new g.CP(g.Y(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.U("mdxautoplayupnext",c)};
g.h.QE=function(a){isNaN(a)||this.A.U("mdxnowautoplaying",a)};
g.h.xE=function(){this.A.U("mdxautoplaycanceled")};
g.h.IO=function(a,b){-1==U7(this.o).playerState?D8(this,a):b&&this.o.seekTo(a)};
g.h.ZG=function(){if(B8(this)){var a=U7(this.o);this.C.La(this.O);a.muted?this.A.mute():this.A.unMute();this.A.setVolume(a.volume);this.O=this.C.R(this.A,"onVolumeChange",this.ME)}};
g.h.xG=function(){this.B.stop();if(!this.o.la()){var a=U7(this.o);a.sb()&&A8(this,new g.JQ(8));z8(this,P7(a));this.B.start()}};
g.h.yG=function(){this.F.stop();this.B.stop();var a=this.o.B.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.F.start()};g.r(E8,g.W);E8.prototype.F=function(a){JGa(this,a.state)};g.r(F8,g.aX);F8.prototype.M=function(){var a=this.B.getOption("remote","receivers");a&&1<a.length&&!this.B.getOption("remote","quickCast")?(this.I=g.vb(a,this.G,this),g.bX(this,(0,g.I)(a,this.G)),a=this.B.getOption("remote","currentReceiver"),this.Af(this.G(a)),this.enable(!0)):this.enable(!1)};
F8.prototype.G=function(a){return a.key};
F8.prototype.zf=function(a){return"cast-selector-receiver"==a?"\u6295\u5c04\u2026":this.I[a].name};
F8.prototype.Id=function(a){g.aX.prototype.Id.call(this,a);this.B.setOption("remote","currentReceiver",this.I[a]);this.D.Jb()};g.r(G8,g.mV);g.h=G8.prototype;g.h.create=function(){AGa(g.NN(g.Y(this.player)));this.D.push(g.mF("yt-remote-before-disconnect",this.GQ,this));this.D.push(g.mF("yt-remote-connection-change",this.rT,this));this.D.push(g.mF("yt-remote-receiver-availability-change",this.ZE,this));this.D.push(g.mF("yt-remote-auto-connect",this.pT,this));this.D.push(g.mF("yt-remote-receiver-resumed",this.oT,this));this.ZE()};
g.h.load=function(){this.player.cancelPlayback();g.mV.prototype.load.call(this);this.B=new y8(this,this.player,this.o);var a=(a=FGa())?a.currentTime:0;var b=w8()?new T7(r8(),void 0):null;0==a&&b&&(a=P7(U7(b)));0!=a&&this.Je(a);IGa(this,this.qn,this.qn);g.D0(this.player.app,6)};
g.h.unload=function(){this.player.U("mdxautoplaycanceled");this.C=this.A;g.Gf(this.B,this.o);this.o=this.B=null;g.mV.prototype.unload.call(this);g.D0(this.player.app,5)};
g.h.W=function(){g.nF(this.D);g.mV.prototype.W.call(this)};
g.h.Th=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.zD.apply(this.B,[a].concat(g.ea(c)))};
g.h.Zk=function(a){this.H=a};
g.h.getAdState=function(){return this.H};
g.h.aL=function(){return this.loaded?this.B.suggestion:null};
g.h.Zf=function(){return this.o?U7(this.o).Zf:!1};
g.h.hasNext=function(){return this.o?U7(this.o).hasNext:!1};
g.h.Je=function(a,b){this.I=a||0;this.player.U("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.I};
g.h.getProgressState=function(){var a=U7(this.o),b=this.player.getVideoData();return{allowSeeking:g.Y(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Kc():!a.isAdPlaying()&&this.player.Kc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.C+N7(a):a.C,isAtLiveHead:1>=(a.D?a.A+N7(a):a.A)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.D?a.A+N7(a):a.A,seekableStart:0<a.B?a.B+N7(a):
a.B}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.Vq=function(){this.o&&this.o.Vq()};
g.h.GQ=function(a){1==a&&(this.G=this.o?U7(this.o):null)};
g.h.rT=function(){var a=w8()?new T7(r8(),void 0):null;if(a){var b=this.C;this.loaded&&this.unload();this.o=a;this.G=null;b.key!=this.A.key&&(this.C=b,this.load())}else g.Ff(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.G)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,P7(a)));this.player.U("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.ZE=function(){this.F=[this.A].concat(CGa());var a=s8()||this.A;H8(this,a);this.player.Ba("onMdxReceiversChange")};
g.h.pT=function(){var a=s8();H8(this,a)};
g.h.oT=function(){this.C=s8()};
g.h.Gc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?J7():H8(this,b)),this.loaded?this.C:this.A;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&J7(),!0):!1}};
g.h.ey=function(){this.o.ey()};
g.h.uc=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.WZ.remote=G8;})(_yt_player);
